FROM apache/spark:3.5.1

USER root

RUN apt-get update && apt-get install -y \
    python3-pip \
    curl \
    python3-venv \
    python3-dev \
    && apt-get clean

# Instala Jupyter Lab e Notebook
RUN pip install --no-cache-dir \
    jupyterlab==4.0.0 \
    notebook==7.0.0 \
    pyspark==3.5.1 \
    delta-spark==3.2.0

# Cria diretório para JARs
RUN mkdir -p /opt/spark/jars

# S3A JARs
RUN curl -L -o /opt/spark/jars/hadoop-aws-3.3.4.jar \
    https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar && \
    curl -L -o /opt/spark/jars/aws-java-sdk-bundle-1.12.262.jar \
    https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar

# Delta JARs
RUN curl -L -o /opt/spark/jars/delta-spark_2.12-3.2.0.jar \
    https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.2.0/delta-spark_2.12-3.2.0.jar && \
    curl -L -o /opt/spark/jars/delta-storage-3.2.0.jar \
    https://repo1.maven.org/maven2/io/delta/delta-storage/3.2.0/delta-storage-3.2.0.jar

# Cria diretório de trabalho e usuário jovyan (padrão Jupyter)
RUN useradd -m -u 1000 jovyan && \
    mkdir -p /home/jovyan/work && \
    chown -R jovyan:jovyan /home/jovyan

# Alternativa: se quiser usar usuário root (mais simples)
# RUN mkdir -p /root/work

# Define diretório de trabalho
WORKDIR /home/jovyan/work

# Expor porta do Jupyter
EXPOSE 8888

# Mantém o container rodando (comando será sobrescrito pelo docker-compose)
CMD ["sleep", "infinity"]